/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-30 18:53:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Modelo.Principal;
import java.util.*;
import ModeloDAO.PrincipalDAO;
import java.sql.*;

public final class config_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("Modelo.Principal");
    _jspx_imports_classes.add("ModeloDAO.PrincipalDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Configuración</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/config.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/barra_lateral.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/panel_principal.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Barra lateral fija con el menÃº principal -->\r\n");
      out.write("    <div class=\"barra-lateral\">\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"bx bxs-coffee-alt\"></i>\r\n");
      out.write("                <span style=\"font-weight: 600;\">Organico Cafeteria</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <i class=\"bx bx-menu\" id=\"btn\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarpr\">\r\n");
      out.write("                    <i class=\"bx bx-grid-alt\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Inicio</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Inicio</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listar\">\r\n");
      out.write("                    <i class=\"bx bxs-store-alt\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Ventas</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Ventas</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarinv\">\r\n");
      out.write("                    <i class=\"bx bx-basket\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Inventario</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Inventario</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarrep\">\r\n");
      out.write("                    <i class=\"bx bxs-report\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Reportes</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Reportes</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarusuario\">\r\n");
      out.write("                    <i class=\"bx bx-cog\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Configuracion</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Configuracion</span>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- Botones de acciones ubicados al final -->\r\n");
      out.write("        <div class=\"acciones\">\r\n");
      out.write("            <form action=\"apertura-caja.jsp\" method=\"get\">\r\n");
      out.write("                <button class=\"boton apertura-caja\">\r\n");
      out.write("                    <i class=\"bx bx-wallet\"></i>\r\n");
      out.write("                    <span class=\"boton-texto\">Apertura y cierre de caja</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <form action=\"Validar\" method=\"POST\">\r\n");
      out.write("                <button type=\"submit\" class=\"boton salir\" name=\"accion\" value=\"Salir\">\r\n");
      out.write("                    <i class=\"bx bx-log-out\"></i>\r\n");
      out.write("                    <span class=\"boton-texto\">Salir</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("            <h1>Configuración</h1>\r\n");
      out.write("\r\n");
      out.write("            <section class=\"mi-usuario\">\r\n");
      out.write("                <h2>Mi Usuario</h2>\r\n");
      out.write("                <form>\r\n");
      out.write("                    <label>Nombres completos</label>\r\n");
      out.write("                    <input type=\"text\" value=\"Roberto Paolo\">\r\n");
      out.write("                    \r\n");
      out.write("                    <label>Apellidos</label>\r\n");
      out.write("                    <input type=\"text\" value=\"CrisÃ³stomo Berrocal\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Número de documento de identidad</label>\r\n");
      out.write("                    <input type=\"text\" value=\"71776762\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Código de empleado</label>\r\n");
      out.write("                    <input type=\"text\" value=\"01\">\r\n");
      out.write("\r\n");
      out.write("                    <label>Teléfono</label>\r\n");
      out.write("                    <input type=\"text\" value=\"934 401 034\">\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("            </section>\r\n");
      out.write("            <section class=\"usuarios\">\r\n");
      out.write("                <h2>Usuarios</h2>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Nombre</th>\r\n");
      out.write("                            <th>Rol</th>\r\n");
      out.write("                            <th>Ãltimo acceso</th>\r\n");
      out.write("                            <th>Editar</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>1</td>\r\n");
      out.write("                            <td>Fredy Nolasco</td>\r\n");
      out.write("                            <td>Administrador</td>\r\n");
      out.write("                            <td>15/11/2024 | 21:53</td>\r\n");
      out.write("                            <td><button>Editar</button></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td>Paolo CrisÃ³stomo</td>\r\n");
      out.write("                            <td>Cajero</td>\r\n");
      out.write("                            <td>15/11/2024 | 10:00</td>\r\n");
      out.write("                            <td><button>Editar</button></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>3</td>\r\n");
      out.write("                            <td>MarÃ­a Casasani</td>\r\n");
      out.write("                            <td>Barista</td>\r\n");
      out.write("                            <td>12/11/2024 | 12:00</td>\r\n");
      out.write("                            <td><button>Editar</button></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section class=\"aperturas-cierres\">\r\n");
      out.write("                <h2>Aperturas y cierres de caja</h2>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Usuario Apertura</th>\r\n");
      out.write("                            <th>Monto Apertura</th>\r\n");
      out.write("                            <th>Monto Cierre</th>\r\n");
      out.write("                            <th>Comentarios</th>\r\n");
      out.write("                            <th>Usuario Cierre</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>4</td>\r\n");
      out.write("                            <td>Fredy Nolasco</td>\r\n");
      out.write("                            <td>200.00</td>\r\n");
      out.write("                            <td>493.50</td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td>Paolo CrisÃ³stomo</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>3</td>\r\n");
      out.write("                            <td>Fredy Nolasco</td>\r\n");
      out.write("                            <td>200.00</td>\r\n");
      out.write("                            <td>493.50</td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td>Paolo CrisÃ³stomo</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const btn = document.querySelector('#btn');\r\n");
      out.write("        const sidebar = document.querySelector('.barra-lateral');\r\n");
      out.write("\r\n");
      out.write("        btn.onclick = function() {\r\n");
      out.write("            sidebar.classList.toggle('active');\r\n");
      out.write("        };\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
