/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-30 18:48:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Modelo.Inventario;
import java.util.*;
import ModeloDAO.InventarioDAO;
import java.sql.*;

public final class inventario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("Modelo.Inventario");
    _jspx_imports_classes.add("ModeloDAO.InventarioDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Inventario - Org?nico Cafeteria</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/barra_lateral.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/editar-inventario.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/inventario.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"barra-lateral\">\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <i class=\"bx bxs-coffee-alt\"></i>\r\n");
      out.write("                <span style=\"font-weight: 600;\">Organico Cafeteria</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <i class=\"bx bx-menu\" id=\"btn\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarpr\">\r\n");
      out.write("                    <i class=\"bx bx-grid-alt\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Inicio</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Inicio</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listar\">\r\n");
      out.write("                    <i class=\"bx bxs-store-alt\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Ventas</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Ventas</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarinv\">\r\n");
      out.write("                    <i class=\"bx bx-basket\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Inventario</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Inventario</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarrep\">\r\n");
      out.write("                    <i class=\"bx bxs-report\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Reportes</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Reportes</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"Controlador?accion=listarusuario\">\r\n");
      out.write("                    <i class=\"bx bx-cog\"></i>\r\n");
      out.write("                    <span class=\"nav-item\">Configuracion</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span class=\"tooltip\">Configuracion</span>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- Botones de acciones ubicados al final -->\r\n");
      out.write("        <div class=\"acciones\">\r\n");
      out.write("            <form action=\"apertura-caja.jsp\" method=\"get\">\r\n");
      out.write("                <button class=\"boton apertura-caja\">\r\n");
      out.write("                    <i class=\"bx bx-wallet\"></i>\r\n");
      out.write("                    <span class=\"boton-texto\">Apertura y cierre de caja</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <form action=\"Validar\" method=\"POST\">\r\n");
      out.write("                <button type=\"submit\" class=\"boton salir\" name=\"accion\" value=\"Salir\">\r\n");
      out.write("                    <i class=\"bx bx-log-out\"></i>\r\n");
      out.write("                    <span class=\"boton-texto\">Salir</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1>Inventario</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    <!-- Contenido principal -->\r\n");
      out.write("        <!-- Resumen de inventario -->\r\n");
      out.write("        <div class=\"resumen-inventario\">\r\n");
      out.write("            <div class=\"tarjeta-inventario\">\r\n");
      out.write("                <i class=\"fa fa-dollar-sign\"></i>\r\n");
      out.write("                <h2>");
      out.print( request.getAttribute("valor_invent") != null ? request.getAttribute("valor_invent") : 0 );
      out.write("</h2>\r\n");
      out.write("                <p>Valor de inventario</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tarjeta-inventario\">\r\n");
      out.write("                <i class=\"fa fa-box\"></i>\r\n");
      out.write("                <h2>");
      out.print( request.getAttribute("stock_invent") != null ? request.getAttribute("stock_invent") : 0 );
      out.write("</h2>\r\n");
      out.write("                <p>Articulos de inventario</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tarjeta-inventario\">\r\n");
      out.write("                <i class=\"fa fa-user\"></i>\r\n");
      out.write("                <h2>");
      out.print( request.getAttribute("cant_prov") != null ? request.getAttribute("cant_prov") : 0 );
      out.write("</h2>\r\n");
      out.write("                <p>Proveedores</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h2>Lista de productos</h2>\r\n");
      out.write("        <!-- Lista de productos -->\r\n");
      out.write("        <div class=\"lista-productos\">\r\n");
      out.write("            <div class=\"barra-busqueda\">\r\n");
      out.write("                <div class=\"campo-lupa\">\r\n");
      out.write("                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Buscar productos...\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <button>Agrupar por: Sin filtro aplicado</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Categoria</th>\r\n");
      out.write("                        <th>Nombre</th>\r\n");
      out.write("                        <th>Descripcion</th>\r\n");
      out.write("                        <th>Stock</th>\r\n");
      out.write("                        <th>Precio</th>\r\n");
      out.write("                        <th>Fecha fabricación</th>\r\n");
      out.write("                        <th>Fecha expiración</th>\r\n");
      out.write("                        <th>Acciones</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
 
                        InventarioDAO dao = new InventarioDAO();
                        List<Inventario> listinv = dao.listarinv();
                        for (Inventario inv : listinv) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print(inv.getId_produc());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getCat_produc());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getNom_produc());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getDescrip_produc());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getStock_produc());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getPrecio());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getFechafab());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(inv.getFechaexp());
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <a href=\"#\" class=\"editar\">Editar</a> | <a href=\"#\" class=\"eliminar\">Eliminar</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Opciones de acci?n -->\r\n");
      out.write("        <div class=\"acciones-inventario\">\r\n");
      out.write("            <form action=\"Controlador?accion=agregarnueprod\" method=\"GET\">\r\n");
      out.write("                <button class=\"boton agregar-producto\" type=\"submit\" name=\"accion\" value=\"agregarnueprod\"  class=\"boton editar-carta\">Agregar Nuevo Producto</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <form action=\"agregar-cat.jsp\" method=\"get\">\r\n");
      out.write("                <button class=\"boton agregar-categoria\">Agregar Nueva Categor?a</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <form action=\"agregar-compra.jsp\" method=\"get\">\r\n");
      out.write("                <button class=\"boton registrar-compra\">Registrar Nueva Compra</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal oculto -->\r\n");
      out.write("    <!-- Modal para modificar producto -->\r\n");
      out.write("    <div id=\"modal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close\">&times;</span>\r\n");
      out.write("            <h1>Modificar Producto</h1>\r\n");
      out.write("            <form action=\"Controlador\">\r\n");
      out.write("                <label for=\"txtNom\">Nombres:</label>\r\n");
      out.write("                <input class=\"form-control\" type=\"text\" id=\"txtNom\" name=\"txtNom\">\r\n");
      out.write("                <label for=\"txtProve\">Proveedor:</label>\r\n");
      out.write("                <input class=\"form-control\" type=\"text\" id=\"txtProve\" name=\"txtProve\">\r\n");
      out.write("                <input type=\"hidden\" name=\"txtId\">\r\n");
      out.write("                <input class=\"btn btn-primary\" type=\"submit\" name=\"accion\" value=\"Actualizar\">\r\n");
      out.write("                <a href=\"inventario.jsp\" class=\"regresar\">Regresar</a>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Tu script original para la barra lateral\r\n");
      out.write("        let btn = document.querySelector('#btn');\r\n");
      out.write("        let sidebar = document.querySelector('.barra-lateral');\r\n");
      out.write("\r\n");
      out.write("        btn.onclick = function () {\r\n");
      out.write("            sidebar.classList.toggle('active');\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Obtener el modal y el bot?n de cerrar\r\n");
      out.write("    var modal = document.getElementById(\"modal\");\r\n");
      out.write("    var closeBtn = document.querySelector(\".close\");\r\n");
      out.write("\r\n");
      out.write("    // Abrir el modal cuando se haga clic en \"Editar\"\r\n");
      out.write("    document.querySelector(\".editar\").addEventListener(\"click\", function(event) {\r\n");
      out.write("        event.preventDefault(); // Evita que se siga el enlace\r\n");
      out.write("        modal.style.display = \"flex\"; // Mostrar el modal\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Cerrar el modal cuando se haga clic en el bot?n de cerrar\r\n");
      out.write("    closeBtn.addEventListener(\"click\", function() {\r\n");
      out.write("        modal.style.display = \"none\"; // Ocultar el modal\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Cerrar el modal si se hace clic fuera de ?l\r\n");
      out.write("    window.addEventListener(\"click\", function(event) {\r\n");
      out.write("        if (event.target === modal) {\r\n");
      out.write("            modal.style.display = \"none\"; // Ocultar el modal si se hace clic fuera de ?l\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
