/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-30 19:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Modelo.Producto;
import java.util.List;
import ModeloDAO.ProductoDAO;

public final class inventario_002dagregar_002dproducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ModeloDAO.ProductoDAO");
    _jspx_imports_classes.add("Modelo.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Editar carta - Org?nico Cafeter?a</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/barra_lateral.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/editar_carta.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n");
      out.write("        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"barra-lateral\">\n");
      out.write("            <div class=\"top\">\n");
      out.write("                <div class=\"logo\">\n");
      out.write("                    <i class=\"bx bxs-coffee-alt\"></i>\n");
      out.write("                    <span style=\"font-weight: 600;\">Organico Cafeteria</span>\n");
      out.write("                </div>\n");
      out.write("                <i class=\"bx bx-menu\" id=\"btn\"></i>\n");
      out.write("            </div>\n");
      out.write("            <ul>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarpr\">\n");
      out.write("                        <i class=\"bx bx-grid-alt\"></i>\n");
      out.write("                        <span class=\"nav-item\">Inicio</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Inicio</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listar\">\n");
      out.write("                        <i class=\"bx bxs-store-alt\"></i>\n");
      out.write("                        <span class=\"nav-item\">Ventas</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Ventas</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarinv\">\n");
      out.write("                        <i class=\"bx bx-basket\"></i>\n");
      out.write("                        <span class=\"nav-item\">Inventario</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Inventario</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarrep\">\n");
      out.write("                        <i class=\"bx bxs-report\"></i>\n");
      out.write("                        <span class=\"nav-item\">Reportes</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Reportes</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarusuario\">\n");
      out.write("                        <i class=\"bx bx-cog\"></i>\n");
      out.write("                        <span class=\"nav-item\">Configuracion</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Configuracion</span>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("            <!-- Botones de acciones ubicados al final -->\n");
      out.write("            <div class=\"acciones\">\n");
      out.write("                <form action=\"apertura-caja.jsp\" method=\"get\">\n");
      out.write("                    <button class=\"boton apertura-caja\">\n");
      out.write("                        <i class=\"bx bx-wallet\"></i>\n");
      out.write("                        <span class=\"boton-texto\">Apertura y cierre de caja</span>\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("                <form action=\"Validar\" method=\"POST\">\n");
      out.write("                    <button type=\"submit\" class=\"boton salir\" name=\"accion\" value=\"Salir\">\n");
      out.write("                        <i class=\"bx bx-log-out\"></i>\n");
      out.write("                        <span class=\"boton-texto\">Salir</span>\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("                    \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--CONTENIDO PRINCIPAL-->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"header\">\n");
      out.write("                <h1>Inventario / Agregar nuevo produto</h1>\n");
      out.write("                <form action=\"Controlador\">\n");
      out.write("                    \n");
      out.write("                    Código del producto (Debe mostrar el cod del producto que se podría autogenerar):<br><!-- comment -->\n");
      out.write("                    <input type=\"text\" name=\"txtCodProd\"><br>\n");
      out.write("                    Fecha de fabricación: <br>\n");
      out.write("                    <input type=\"text\" name=\"txtFechFab\"><br>\n");
      out.write("                    Fecha de vencimiento <br>\n");
      out.write("                    <input type=\"text\" name=\"txtFechaVenc\"><br>\n");
      out.write("                    Nombre del producto <br>\n");
      out.write("                    <input type=\"text\" name=\"txtNombre\"><br>\n");
      out.write("                    Categoría <br>\n");
      out.write("                        <select>\n");
      out.write("                            <option>Sin categoria</option>\n");
      out.write("                            <option>Categoria1</option>\n");
      out.write("                            <option>Categoria1</option>\n");
      out.write("                        </select> <br>                    \n");
      out.write("                    Tipo de producto <br>\n");
      out.write("                        <select>\n");
      out.write("                            <option>Sin tipo</option>\n");
      out.write("                            <option>Materia prima</option>\n");
      out.write("                            <option>Producto preparado</option>\n");
      out.write("                        </select> <br>              \n");
      out.write("                    Stock disponible<br>\n");
      out.write("                    <input type=\"text\" name=\"txtStockDisp\"><br>\n");
      out.write("                    Precio unitario<br>\n");
      out.write("                    <input type=\"text\" name=\"txtStockDisp\"><br>\n");
      out.write("                    Valor de inventario de producto<br>\n");
      out.write("                    <input type=\"text\" name=\"txtStockDisp\"><br>\n");
      out.write("                    Nombre del proveedor <br>\n");
      out.write("                        <select>\n");
      out.write("                            <option>Sin proveedor</option>\n");
      out.write("                            <option>Proveedor1</option>\n");
      out.write("                            <option>Proveedor2</option>\n");
      out.write("                        </select> <br>\n");
      out.write("                    <!-- Botón -->\n");
      out.write("                    <input type=\"submit\" name =\"accion\" value=\"agregar\"\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <h2>Debajo de esto mostrar el producto para editar</h2>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        let btn = document.querySelector('#btn');\n");
      out.write("        let sidebar = document.querySelector('.barra-lateral');\n");
      out.write("\n");
      out.write("        btn.onclick = function () {\n");
      out.write("            sidebar.classList.toggle('active');\n");
      out.write("        };\n");
      out.write("    </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
