/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-30 21:10:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import Modelo.Producto;
import ModeloDAO.ProductoDAO;
import Config.Conexion;
import java.sql.*;

public final class nueva_002dventa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("ModeloDAO.ProductoDAO");
    _jspx_imports_classes.add("Modelo.Producto");
    _jspx_imports_classes.add("Config.Conexion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title> Registrar Venta - Orgánico Cafeteria</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/barra_lateral.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/nueva-venta.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!--Barra Lateral-->\n");
      out.write("        <div class=\"barra-lateral\">\n");
      out.write("            <div class=\"top\">\n");
      out.write("                <div class=\"logo\">\n");
      out.write("                    <i class=\"bx bxs-coffee-alt\"></i>\n");
      out.write("                    <span style=\"font-weight: 600;\">Organico Cafeteria</span>\n");
      out.write("                </div>\n");
      out.write("                <i class=\"bx bx-menu\" id=\"btn\"></i>\n");
      out.write("            </div>\n");
      out.write("            <ul>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarpr\">\n");
      out.write("                        <i class=\"bx bx-grid-alt\"></i>\n");
      out.write("                        <span class=\"nav-item\">Inicio</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Inicio</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listar\">\n");
      out.write("                        <i class=\"bx bxs-store-alt\"></i>\n");
      out.write("                        <span class=\"nav-item\">Ventas</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Ventas</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarinv\">\n");
      out.write("                        <i class=\"bx bx-basket\"></i>\n");
      out.write("                        <span class=\"nav-item\">Inventario</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Inventario</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarrep\">\n");
      out.write("                        <i class=\"bx bxs-report\"></i>\n");
      out.write("                        <span class=\"nav-item\">Reportes</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Reportes</span>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"Controlador?accion=listarusuario\">\n");
      out.write("                        <i class=\"bx bx-cog\"></i>\n");
      out.write("                        <span class=\"nav-item\">Configuracion</span>\n");
      out.write("                    </a>\n");
      out.write("                    <span class=\"tooltip\">Configuracion</span>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("            <!-- Botones de acciones ubicados al final -->\n");
      out.write("            <div class=\"acciones\">\n");
      out.write("                <form action=\"apertura-caja.jsp\" method=\"get\">\n");
      out.write("                    <button class=\"boton apertura-caja\">\n");
      out.write("                        <i class=\"bx bx-wallet\"></i>\n");
      out.write("                        <span class=\"boton-texto\">Apertura y cierre de caja</span>\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("                <form action=\"Validar\" method=\"POST\">\n");
      out.write("                    <button type=\"submit\" class=\"boton salir\" name=\"accion\" value=\"Salir\">\n");
      out.write("                        <i class=\"bx bx-log-out\"></i>\n");
      out.write("                        <span class=\"boton-texto\">Salir</span>\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--Contenido principal-->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"header\">\n");
      out.write("                <h1>VENTA / REGISTRAR NUEVA VENTA</h1>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"grid-container\">\n");
      out.write("                <div class=\"izquierda\">\n");
      out.write("                    <div class=\"categoria-display\">\n");
      out.write("                        <h3>Categorias</h3>\n");
      out.write("                        <!-- Control buttons -->\n");
      out.write("                        <div id=\"contenedor-btn\" class=\"grupo-c\" action=\"C\">\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("/Controlador?btnselec=8\" class=\"btn\" target=\"listarproductos\">Mostrar todo</a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("Controlador?btnselec=1\" class=\"btn\" target=\"listarproductos\">Bebidas Calientes</a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("Controlador?btnselec=2\" class=\"btn\" target=\"listarproductos\">Postres</a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("Controlador?btnselec=4\" class=\"btn\" target=\"listarproductos\">Bebidas Frías</a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("Controlador?btnselec=5\" class=\"btn\" target=\"listarproductos\">Jugos</a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("Controlador?btnselec=6\" class=\"btn\" target=\"listarproductos\">Sandwiches</a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath());
      out.write("Controlador?btnselec=7\" class=\"btn\" target=\"listarproductos\">Hamburguesas</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>                   \n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"lista-productos\">\n");
      out.write("                            <div class=\"t_header\">\n");
      out.write("                                <div>\n");
      out.write("                                    <h3>Lista de Productos</h3>\n");
      out.write("                                    \n");
      out.write("                                </div>                             \n");
      out.write("                                <div >\n");
      out.write("                                    <iframe name=\"listarproductos\" style=\"height: 100%; width: 100%\" ></iframe>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"tabla-body\" id=\"tabla-productos\">\n");
      out.write("                            </div> <!-- /.card-body -->\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"derecha\">\n");
      out.write("                    <div class=\"tabla-body2\" id=\"tabla-productos2\">\n");
      out.write("                        <table class=\"tableP\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th style=\"width: 10px\">ID</th>\n");
      out.write("                                    <th>Producto</th>\n");
      out.write("                                    <th>Precio</th>\n");
      out.write("                                    <th style=\"width: 40px\">Opciones</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr class=\"align-middle\">\n");
      out.write("                                    <th scope=\"row\"></td>\n");
      out.write("                                    <td></td>\n");
      out.write("                                    <td></td>\n");
      out.write("                                    <td style=\"width:120px\"> <input type=\"number\" style=\"width: 40px\"><a style=\"font-size: 12px\">  Eliminar</a></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                    <div >\n");
      out.write("                        <div class=\"c_header\">\n");
      out.write("                            <h3>Detalles de Cliente</h3>\n");
      out.write("                        </div>\n");
      out.write("                        <form class=\"form-nventa\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-6\">\n");
      out.write("                                    <label>Tipo de Comprobante</label>\n");
      out.write("                                    <select>\n");
      out.write("                                        <option></option>\n");
      out.write("                                        <option>Factura</option>\n");
      out.write("                                        <option>Boleta</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-6\" >\n");
      out.write("                                    <label>Cliente</label>\n");
      out.write("                                    <input type=\"text\" value=\"\" >\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-6\">\n");
      out.write("                                    <label>Metodo de Pago</label>\n");
      out.write("                                    <select>\n");
      out.write("                                        <option></option>\n");
      out.write("                                        <option>Efectivo</option>\n");
      out.write("                                        <option>Tarjeta</option>\n");
      out.write("                                    </select> \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"comen\">\n");
      out.write("                                    <label>Agregar Comentarios:</label>\n");
      out.write("                                    <textarea class=\"form-control\"></textarea>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"acciones-nventa\">\n");
      out.write("                        <button class=\"boton cancelar-orden\" >Cancelar Orden</button>\n");
      out.write("                        <button class=\"boton finalizar-orden\" onclick=\"location.href = 'nueva-venta-2.jsp'\">Finalizar Orden</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function mostrarTabla() {\n");
      out.write("            // Obtener el elemento de la tabla por su id\n");
      out.write("            const tabla = document.getElementById('tabla-productos');\n");
      out.write("            // Cambiar el estilo a 'block' para hacerla visible\n");
      out.write("            tabla.style.display = 'block';\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        // Tu script original para la barra lateral\n");
      out.write("        let btn = document.querySelector('#btn');\n");
      out.write("        let sidebar = document.querySelector('.barra-lateral');\n");
      out.write("\n");
      out.write("        btn.onclick = function () {\n");
      out.write("            sidebar.classList.toggle('active');\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        // Obtener el modal y el botón de cerrar\n");
      out.write("        var modal = document.getElementById(\"modal\");\n");
      out.write("        var closeBtn = document.querySelector(\".close\");\n");
      out.write("\n");
      out.write("        // Abrir el modal cuando se haga clic en \"Editar\"\n");
      out.write("        document.querySelector(\".editar\").addEventListener(\"click\", function (event) {\n");
      out.write("            event.preventDefault(); // Evita que se siga el enlace\n");
      out.write("            modal.style.display = \"flex\"; // Mostrar el modal\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Cerrar el modal cuando se haga clic en el botón de cerrar\n");
      out.write("        closeBtn.addEventListener(\"click\", function () {\n");
      out.write("            modal.style.display = \"none\"; // Ocultar el modal\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Cerrar el modal si se hace clic fuera de él\n");
      out.write("        window.addEventListener(\"click\", function (event) {\n");
      out.write("            if (event.target === modal) {\n");
      out.write("                modal.style.display = \"none\"; // Ocultar el modal si se hace clic fuera de él\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        table_headings.forEach((head, i) => {\n");
      out.write("            let sort_asc = true;\n");
      out.write("            head.onclick = () => {\n");
      out.write("                table_headings.forEach(head => head.classList.remove('active'));\n");
      out.write("                head.classList.add('active');\n");
      out.write("\n");
      out.write("                document.querySelectorAll('td').forEach(td => td.classList.remove('active'));\n");
      out.write("                table_rows.forEach(row => {\n");
      out.write("                    row.querySelectorAll('td')[i].classList.add('active');\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                head.classList.toggle('asc', sort_asc);\n");
      out.write("                sort_asc = head.classList.contains('asc') ? false : true;\n");
      out.write("\n");
      out.write("                sortTable(i, sort_asc);\n");
      out.write("            };\n");
      out.write("        });\n");
      out.write("\n");
      out.write("\n");
      out.write("        function sortTable(column, sort_asc) {\n");
      out.write("            [...table_rows].sort((a, b) => {\n");
      out.write("                let first_row = a.querySelectorAll('td')[column].textContent.toLowerCase(),\n");
      out.write("                        second_row = b.querySelectorAll('td')[column].textContent.toLowerCase();\n");
      out.write("\n");
      out.write("                return sort_asc ? (first_row < second_row ? 1 : -1) : (first_row < second_row ? -1 : 1);\n");
      out.write("            })\n");
      out.write("                    .map(sorted_row => document.querySelector('tbody').appendChild(sorted_row));\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
