/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-29 23:03:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import Modelo.Producto;
import ModeloDAO.ProductoDAO;
import Config.Conexion;
import java.sql.*;

public final class nueva_002dventa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("ModeloDAO.ProductoDAO");
    _jspx_imports_classes.add("Modelo.Producto");
    _jspx_imports_classes.add("Config.Conexion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title> Registrar Venta - Orgánico Cafeteria</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/barra_lateral.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/nueva-venta.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"adminlte.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\r\n");
      out.write("    <!--Barra Lateral-->\r\n");
      out.write("    <div class=\"barra-lateral\">\r\n");
      out.write("        <h2>ORGÁNICO CAFETERÍA</h2>\r\n");
      out.write("        <!-- Opciones del menú -->\r\n");
      out.write("        <a href=\"principal.jsp\" class=\"opcion-menu\">\r\n");
      out.write("            <i class=\"fa fa-home\"></i>\r\n");
      out.write("            <span>Inicio</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"ventas.jsp\" class=\"opcion-menu\">\r\n");
      out.write("            <i class=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("            <span>Venta</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"inventario.jsp\" class=\"opcion-menu activo\">\r\n");
      out.write("            <i class=\"fa fa-boxes\"></i>\r\n");
      out.write("            <span>Inventario</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"reportes.jsp\" class=\"opcion-menu\">\r\n");
      out.write("            <i class=\"fa fa-chart-bar\"></i>\r\n");
      out.write("            <span>Reportes</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"config.jsp\" class=\"opcion-menu\">\r\n");
      out.write("            <i class=\"fa fa-cogs\"></i>\r\n");
      out.write("            <span>Configuración</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Botones de acciones ubicados al final -->\r\n");
      out.write("        <div class=\"acciones\">\r\n");
      out.write("            <form action=\"apertura-caja.jsp\" method=\"get\">\r\n");
      out.write("                <button class=\"boton apertura-caja\">Apertura y cierre de caja</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <button class=\"boton salir\"><i class=\"fa fa-sign-out-alt\"></i>Salir</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Contenido principal-->\r\n");
      out.write("    <div class=\"contenido-principal\">\r\n");
      out.write("        <h1>VENTA / REGISTRAR NUEVA VENTA</h1>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"grid-container\">\r\n");
      out.write("            <div class=\"grid-left\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Categorias -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"categoria-display\">\r\n");
      out.write("                        <h3>Categorias</h3>\r\n");
      out.write("                        <div id=\"contenedor-btn\" class=\"grupo-c\">\r\n");
      out.write("                            <a href=\"productoControlador?btnselec=0\" class=\"btn\">Mostrar todo</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/productoControlador?btnselec=1\" class=\"btn\">Bebidas Calientes</a>\r\n");
      out.write("                            <a href=\"productoControlador?btnselec=2\" class=\"btn\">Postres</a>\r\n");
      out.write("                            <a href=\"productoControlador?btnselec=4\" class=\"btn\">Bebidas Frías</a>\r\n");
      out.write("                            <a href=\"productoControlador?btnselec=5\" class=\"btn\">Jugos</a>\r\n");
      out.write("                            <a href=\"productoControlador?btnselec=6\" class=\"btn\">Sandwiches</a>\r\n");
      out.write("                            <a href=\"productoControlador?btnselec=7\" class=\"btn\">Hamburguesas</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>                   \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Lista de productos -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"lista-productos\">\r\n");
      out.write("                        <h3>Lista de Productos</h3>\r\n");
      out.write("                        <div class=\"barra-busqueda\">\r\n");
      out.write("                            <form action=\"\">\r\n");
      out.write("                                <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Buscar productos...\">\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\" style=\"display: none\" id=\"tabla-productos\">\r\n");
      out.write("                           ");

                             Producto producto = (Producto) request.getAttribute("producto");
    if                          (producto != null) {
                            
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th style=\"width: 10px\">ID</th>\r\n");
      out.write("                                        <th>Producto</th>\r\n");
      out.write("                                        <th>Precio</th>\r\n");
      out.write("                                        <th style=\"width: 40px\">Opciones</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                  \r\n");
      out.write("                                    <tr class=\"align-middle\">\r\n");
      out.write("                                        <td>");
      out.print(producto.getID());
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print(producto.getNombre());
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print(producto.getPrecio());
      out.write("</td>\r\n");
      out.write("                                        <td><a>Añadir</a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div> <!-- /.card-body -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"grid-rigth\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Lista de Compras</h2>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <table class=\"table \">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"width: 10px\">ID</th>\r\n");
      out.write("                                    <th>Producto</th>\r\n");
      out.write("                                    <th>Precio</th>\r\n");
      out.write("                                    <th style=\"width: 40px\">Opciones</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr class=\"align-middle\" >\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td style=\"width: 150px\"> <input type=\"number\" style=\"width: 40px\"><a>  Eliminar</a></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"align-middle\">\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"align-middle\">\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"align-middle\">\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div> <!-- /.card-body -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div >\r\n");
      out.write("                    <form class=\"form-nventa\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label>Tipo de Comprobante</label>\r\n");
      out.write("                            <select>\r\n");
      out.write("                                <option></option>\r\n");
      out.write("                                <option>Factura</option>\r\n");
      out.write("                                <option>Boleta</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\" style=\"margin-top: 15px\">\r\n");
      out.write("                            <label>Cliente</label>\r\n");
      out.write("                            <input type=\"text\" value=\"\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label>Metodo de Pago</label>\r\n");
      out.write("                            <select>\r\n");
      out.write("                                <option></option>\r\n");
      out.write("                                <option>Efectivo</option>\r\n");
      out.write("                                <option>Tarjeta</option>\r\n");
      out.write("                            </select> \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <label>Agregar Comentarios</label>\r\n");
      out.write("                        <textarea class=\"form-control\" rows=\"3\" placeholder=\"Enter ...\"></textarea>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"acciones-nventa\">\r\n");
      out.write("                    <button class=\"boton cancelar-orden\" >Cancelar Orden</button>\r\n");
      out.write("                    <button class=\"boton finalizar-orden\" onclick=\"location.href='nueva-venta-2.jsp'\">Finalizar Orden</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    function mostrarTabla() {\r\n");
      out.write("        // Obtener el elemento de la tabla por su id\r\n");
      out.write("        const tabla = document.getElementById('tabla-productos');\r\n");
      out.write("        // Cambiar el estilo a 'block' para hacerla visible\r\n");
      out.write("        tabla.style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
