/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-30 18:54:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Config.Conexion;
import Modelo.Pedidos;
import java.util.*;
import ModeloDAO.PedidosDAO;
import java.sql.*;

public final class reportes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Modelo.Pedidos");
    _jspx_imports_classes.add("ModeloDAO.PedidosDAO");
    _jspx_imports_classes.add("Config.Conexion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Reportes - Orgánico Cafeteria</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/barra_lateral.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reportes.css\">\n");
      out.write("        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css\" />\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!--Barra Lateral-->\n");
      out.write("        <div class=\"barra-lateral\">\n");
      out.write("        <div class=\"top\">\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <i class=\"bx bxs-coffee-alt\"></i>\n");
      out.write("                <span style=\"font-weight: 600;\">Organico Cafeteria</span>\n");
      out.write("            </div>\n");
      out.write("            <i class=\"bx bx-menu\" id=\"btn\"></i>\n");
      out.write("        </div>\n");
      out.write("        <ul>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Controlador?accion=listarpr\">\n");
      out.write("                    <i class=\"bx bx-grid-alt\"></i>\n");
      out.write("                    <span class=\"nav-item\">Inicio</span>\n");
      out.write("                </a>\n");
      out.write("                <span class=\"tooltip\">Inicio</span>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Controlador?accion=listar\">\n");
      out.write("                    <i class=\"bx bxs-store-alt\"></i>\n");
      out.write("                    <span class=\"nav-item\">Ventas</span>\n");
      out.write("                </a>\n");
      out.write("                <span class=\"tooltip\">Ventas</span>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Controlador?accion=listarinv\">\n");
      out.write("                    <i class=\"bx bx-basket\"></i>\n");
      out.write("                    <span class=\"nav-item\">Inventario</span>\n");
      out.write("                </a>\n");
      out.write("                <span class=\"tooltip\">Inventario</span>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Controlador?accion=listarrep\">\n");
      out.write("                    <i class=\"bx bxs-report\"></i>\n");
      out.write("                    <span class=\"nav-item\">Reportes</span>\n");
      out.write("                </a>\n");
      out.write("                <span class=\"tooltip\">Reportes</span>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Controlador?accion=listarusuario\">\n");
      out.write("                    <i class=\"bx bx-cog\"></i>\n");
      out.write("                    <span class=\"nav-item\">Configuracion</span>\n");
      out.write("                </a>\n");
      out.write("                <span class=\"tooltip\">Configuracion</span>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("        <!-- Botones de acciones ubicados al final -->\n");
      out.write("        <div class=\"acciones\">\n");
      out.write("            <form action=\"apertura-caja.jsp\" method=\"get\">\n");
      out.write("                <button class=\"boton apertura-caja\">\n");
      out.write("                    <i class=\"bx bx-wallet\"></i>\n");
      out.write("                    <span class=\"boton-texto\">Apertura y cierre de caja</span>\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("            <form action=\"Validar\" method=\"POST\">\n");
      out.write("                <button type=\"submit\" class=\"boton salir\" name=\"accion\" value=\"Salir\">\n");
      out.write("                    <i class=\"bx bx-log-out\"></i>\n");
      out.write("                    <span class=\"boton-texto\">Salir</span>\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"header\">\n");
      out.write("                <h1>Reportes</h1>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stats\">\n");
      out.write("                <div class=\"small-box\" style=\"background-color: burlywood;\">\n");
      out.write("                    <div class=\"inner\">\n");
      out.write("                        <h3>150</h3>\n");
      out.write("\n");
      out.write("                        <p>Total de Ventas</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"icon\">\n");
      out.write("                        <i class=\"bx bxs-cart\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"#\" class=\"small-box-footer\">\n");
      out.write("                        Más detalles <i class=\"bx bxs-right-arrow-circle\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"small-box\" style=\"background-color: rgb(222, 135, 193);\">\n");
      out.write("                    <div class=\"inner\">\n");
      out.write("                        <h3>53<sup style=\"font-size: 20px\">%</sup></h3>\n");
      out.write("\n");
      out.write("                        <p>Cantidad de Ventas</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"icon\">\n");
      out.write("                        <i class=\"bx bx-stats\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Controlador?accion=listarinv\" class=\"small-box-footer\">\n");
      out.write("                        Más detalles <i class=\"bx bxs-right-arrow-circle\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"small-box\" style=\"background-color:darksalmon;\">\n");
      out.write("                    <div class=\"inner\">\n");
      out.write("                        <h3>65</h3>\n");
      out.write("\n");
      out.write("                        <p>Productos a la Venta</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"icon\">\n");
      out.write("                        <i class=\"bx bxs-pie-chart-alt-2\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"#\" class=\"small-box-footer\">\n");
      out.write("                        Más detalles <i class=\"bx bxs-right-arrow-circle\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"graf\">\n");
      out.write("                <div class=\"titulo\">\n");
      out.write("                    <h2>Ingresos</h2>\n");
      out.write("                    <div class=\"menu\">\n");
      out.write("                        <i class=\"bx bx-minus icon\"></i>\n");
      out.write("                        <i class=\"bx bx-x icon\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"grafico\">\n");
      out.write("                    <div id=\"chart\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"ctrls\">\n");
      out.write("                    <h3>Frecuencia</h3>\n");
      out.write("                    <div class=\"frecuencia\">\n");
      out.write("                        <div class=\"frec\">\n");
      out.write("                            <label for=\"\" class=\"sidebar-label-container\">\n");
      out.write("                                <input type=\"radio\" name=\"test\">\n");
      out.write("                                <span class=\"checkmark\"></span> Semanal\n");
      out.write("                            </label>\n");
      out.write("                            <label for=\"\" class=\"sidebar-label-container\">\n");
      out.write("                                <input type=\"radio\" name=\"test\">\n");
      out.write("                                <span class=\"checkmark\"></span> Mensual\n");
      out.write("                            </label>\n");
      out.write("                            <label for=\"\" class=\"sidebar-label-container\">\n");
      out.write("                                <input type=\"radio\" name=\"test\">\n");
      out.write("                                <span class=\"checkmark\"></span> Semestre\n");
      out.write("                            </label>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <h3>Rango</h3>\n");
      out.write("                    <div class=\"range\" id=\"range\">\n");
      out.write("                        <i class=\"bx bx-calendar\"></i>&nbsp;\n");
      out.write("                        <span></span> <b class=\"bx bxs-down-arrow\"></b>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <h3>Año</h3>\n");
      out.write("                    <div class=\"año\">\n");
      out.write("                        <div class=\"select-año\">\n");
      out.write("                            <span class=\"selected-año\">2024</span>\n");
      out.write("                            <div class=\"caret\"></div>\n");
      out.write("                        </div>\n");
      out.write("                        <ul class=\"año-dd\">\n");
      out.write("                            <li>2020</li>\n");
      out.write("                            <li>2021</li>\n");
      out.write("                            <li>2022</li>\n");
      out.write("                            <li>2023</li>\n");
      out.write("                            <li class=\"active\">2024</li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"graf2\">\n");
      out.write("                <div class=\"cant-ped\">\n");
      out.write("                    <div class=\"titulo\">\n");
      out.write("                        <h3>Proporción de Ventas por Categorí­a </h3>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"grafico\">\n");
      out.write("                        <div id=\"chart2\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"prod-ven\">\n");
      out.write("                    <div class=\"titulo\">\n");
      out.write("                        <h3>Productos Más Vendidos en la Semana</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"grafico\">\n");
      out.write("                        <div id=\"chart3\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"graf3\">\n");
      out.write("                <div class=\"cat-ven\">\n");
      out.write("                    <div class=\"titulo\">\n");
      out.write("                        <h3>Comparación de Cantidad de Pedidos</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"grafico\">\n");
      out.write("                        <div id=\"chart4\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro-cat\" id=\"ped_ta\">\n");
      out.write("                    <section class=\"tabla-titulo\">\n");
      out.write("                        <h3>Lista de Pedidos</h3>\n");
      out.write("                        <div class=\"export__file\">\n");
      out.write("                            <label for=\"export-file\" class=\"export__file-btn\" title=\"Export File\"></label>\n");
      out.write("                            <input type=\"checkbox\" id=\"export-file\">\n");
      out.write("                            <div class=\"export__file-options\">\n");
      out.write("                                <label>Export As &nbsp; &#10140;</label>\n");
      out.write("                                <label for=\"export-file\" id=\"toPDF\">PDF <i class=\"bx bxs-file-pdf\"></i></label>\n");
      out.write("                                <label for=\"export-file\" id=\"toJSON\">JSON <i class=\"bx bxs-file-json\"></i></label>\n");
      out.write("                                <label for=\"export-file\" id=\"toCSV\">CSV <i class=\"bx bx-file\"></i></label>\n");
      out.write("                                <label for=\"export-file\" id=\"toEXCEL\">EXCEL <i class=\"bx bx-table\"></i></label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("                    <section class=\"tabla-body\">\n");
      out.write("                        <table class=\"t-pedidos\" id=\"t-pedidos\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr class=\"table-info\">\n");
      out.write("                                    <th scope=\"col\">Codigo</th>\n");
      out.write("                                    <th scope=\"col\">Cantidad de Productos</th>\n");
      out.write("                                    <th scope=\"col\">Total</th>\n");
      out.write("                                    <th scope=\"col\">Fecha</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                ");
 
                                    PedidosDAO dao = new PedidosDAO();
                                    List<Pedidos> listpedio = dao.listped();
                                    for (Pedidos ped : listpedio) {
                                
      out.write("\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>");
      out.print(ped.getId_ped());
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print(ped.getCant_tot());
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print(ped.getTotped());
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print(ped.getFecped());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                ");
}
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </section>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        let btn = document.querySelector('#btn');\n");
      out.write("        let sidebar = document.querySelector('.barra-lateral');\n");
      out.write("\n");
      out.write("        btn.onclick = function () {\n");
      out.write("            sidebar.classList.toggle('active');\n");
      out.write("        };\n");
      out.write("    </script>\n");
      out.write("<script src=\"../js/moment.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/apexcharts\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/jquery/latest/jquery.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"../js/daterangepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css\" />\n");
      out.write("<script>\n");
      out.write("    var options = {\n");
      out.write("        series: [{\n");
      out.write("        name: \"Desktops\",\n");
      out.write("                data: [10, 41, 35, 51, 49, 62, 69, 91, 148]\n");
      out.write("        }],\n");
      out.write("                chart: {\n");
      out.write("                height: 350,\n");
      out.write("                        type: 'line',\n");
      out.write("                        zoom: {\n");
      out.write("                        enabled: false\n");
      out.write("                        }\n");
      out.write("                },\n");
      out.write("                dataLabels: {\n");
      out.write("                enabled: false\n");
      out.write("                },\n");
      out.write("                stroke: {\n");
      out.write("                curve: 'straight'\n");
      out.write("                },\n");
      out.write("                title: {\n");
      out.write("                text: '',\n");
      out.write("                        align: 'left'\n");
      out.write("                },\n");
      out.write("                grid: {\n");
      out.write("                row: {\n");
      out.write("                colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns\n");
      out.write("                        opacity: 0.5\n");
      out.write("                }\n");
      out.write("                },\n");
      out.write("                xaxis: {\n");
      out.write("                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep']\n");
      out.write("                }\n");
      out.write("        };\n");
      out.write("        var chart = new ApexCharts(document.querySelector(\"#chart\"), options);\n");
      out.write("        chart.render();\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("            var options = {\n");
      out.write("            series: [{\n");
      out.write("                name: 'Series 1',\n");
      out.write("                data: [20, 100, 40, 30, 50, 80, 33]\n");
      out.write("            }],\n");
      out.write("            chart: {\n");
      out.write("                height: 350,\n");
      out.write("                type: 'radar'\n");
      out.write("            },\n");
      out.write("            dataLabels: {\n");
      out.write("                enabled: true\n");
      out.write("            },\n");
      out.write("            plotOptions: {\n");
      out.write("                radar: {\n");
      out.write("                    size: 140,\n");
      out.write("                    polygons: {\n");
      out.write("                        strokeColors: '#e9e9e9',\n");
      out.write("                        fill: {\n");
      out.write("                            colors: ['#f8f8f8', '#fff']\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            title: {\n");
      out.write("                text: '' /*CHE ES PARA AGREGAR TEXTO AQUI Y ASI*/\n");
      out.write("            },\n");
      out.write("            colors: ['#FF4560'],\n");
      out.write("            markers: {\n");
      out.write("                size: 4,\n");
      out.write("                colors: ['#fff'],\n");
      out.write("                strokeColor: '#FF4560',\n");
      out.write("                strokeWidth: 2\n");
      out.write("            },\n");
      out.write("            tooltip: {\n");
      out.write("                y: {\n");
      out.write("                    formatter: function (val) {\n");
      out.write("                        return val;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            xaxis: {\n");
      out.write("                categories: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']\n");
      out.write("            },\n");
      out.write("            yaxis: {\n");
      out.write("                labels: {\n");
      out.write("                    formatter: function (val, i) {\n");
      out.write("                        if (i % 2 === 0) {\n");
      out.write("                            return val;\n");
      out.write("                        } else {\n");
      out.write("                            return '';\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        var chart = new ApexCharts(document.querySelector(\"#chart2\"), options);\n");
      out.write("        chart.render();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("                var options = {\n");
      out.write("                series: [76, 67, 61, 90],\n");
      out.write("                chart: {\n");
      out.write("                    height: 390,\n");
      out.write("                    type: 'radialBar'\n");
      out.write("                },\n");
      out.write("                plotOptions: {\n");
      out.write("                    radialBar: {\n");
      out.write("                        offsetY: 0,\n");
      out.write("                        startAngle: 0,\n");
      out.write("                        endAngle: 270,\n");
      out.write("                        hollow: {\n");
      out.write("                            margin: 5,\n");
      out.write("                            size: '30%',\n");
      out.write("                            background: 'transparent',\n");
      out.write("                            image: undefined\n");
      out.write("                        },\n");
      out.write("                        dataLabels: {\n");
      out.write("                            name: {\n");
      out.write("                                show: false\n");
      out.write("                            },\n");
      out.write("                            value: {\n");
      out.write("                                show: false\n");
      out.write("                            }\n");
      out.write("                        },\n");
      out.write("                        barLabels: {\n");
      out.write("                            enabled: true,\n");
      out.write("                            useSeriesColors: true,\n");
      out.write("                            offsetX: -8,\n");
      out.write("                            fontSize: '16px',\n");
      out.write("                            formatter: function (seriesName, opts) {\n");
      out.write("                                return seriesName + \":  \" + opts.w.globals.series[opts.seriesIndex];\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                colors: ['#1ab7ea', '#0084ff', '#39539E', '#0077B5'],\n");
      out.write("                labels: ['Vimeo', 'Messenger', 'Facebook', 'LinkedIn'],\n");
      out.write("                responsive: [{\n");
      out.write("                    breakpoint: 480,\n");
      out.write("                    options: {\n");
      out.write("                        legend: {\n");
      out.write("                            show: false\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }]\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            var chart = new ApexCharts(document.querySelector(\"#chart3\"), options);\n");
      out.write("            chart.render();\n");
      out.write("</script> \n");
      out.write("\n");
      out.write("<script> \n");
      out.write("    var options = {\n");
      out.write("            series: [{\n");
      out.write("                data: [44, 55, 41, 64, 22, 43, 21]\n");
      out.write("            }, {\n");
      out.write("                data: [53, 32, 33, 52, 13, 44, 32]\n");
      out.write("            }],\n");
      out.write("            chart: {\n");
      out.write("                type: 'bar',\n");
      out.write("                height: 430\n");
      out.write("            },\n");
      out.write("            plotOptions: {\n");
      out.write("                bar: {\n");
      out.write("                    horizontal: true,\n");
      out.write("                    dataLabels: {\n");
      out.write("                        position: 'top'\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            dataLabels: {\n");
      out.write("                enabled: true,\n");
      out.write("                offsetX: -6,\n");
      out.write("                style: {\n");
      out.write("                    fontSize: '12px',\n");
      out.write("                    colors: ['#fff']\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            stroke: {\n");
      out.write("                show: true,\n");
      out.write("                width: 1,\n");
      out.write("                colors: ['#fff']\n");
      out.write("            },\n");
      out.write("            tooltip: {\n");
      out.write("                shared: true,\n");
      out.write("                intersect: false\n");
      out.write("            },\n");
      out.write("            xaxis: {\n");
      out.write("                categories: [2001, 2002, 2003, 2004, 2005, 2006, 2007]\n");
      out.write("            }\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        var chart = new ApexCharts(document.querySelector(\"#chart4\"), options);\n");
      out.write("        chart.render();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    const allMenu = document.querySelectorAll('.menu');\n");
      out.write("    allMenu.forEach(item => {\n");
      out.write("        const icon = item.querySelector('.icon');\n");
      out.write("        const menuLink = item.querySelector('.menu-link');\n");
      out.write("\n");
      out.write("        icon.addEventListener('click', function () {\n");
      out.write("            menuLink.classList.toggle('show');\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("        $(function () {\n");
      out.write("            var start = moment().subtract(29, 'days');\n");
      out.write("            var end = moment();\n");
      out.write("\n");
      out.write("            function cb(start, end) {\n");
      out.write("                $('#range span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));\n");
      out.write("            }\n");
      out.write("            $('#range').daterangepicker({\n");
      out.write("                startDate: start,\n");
      out.write("                endDate: end,\n");
      out.write("                ranges: {\n");
      out.write("                    'Última Semana': [moment().subtract(6, 'days'), moment()],\n");
      out.write("                    'Últimos 30 dí­as': [moment().subtract(29, 'days'), moment()],\n");
      out.write("                    'Este Mes': [moment().startOf('month'), moment().endOf('month')],\n");
      out.write("                    'Mes Pasado': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]\n");
      out.write("                }\n");
      out.write("            }, cb);\n");
      out.write("\n");
      out.write("            cb(start, end);\n");
      out.write("\n");
      out.write("        });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("        const dropdowns = document.querySelectorAll('.año');\n");
      out.write("        dropdowns.forEach(dropdown => {\n");
      out.write("            const select = dropdown.querySelector('.select-año');\n");
      out.write("            const caret = dropdown.querySelector('.caret');\n");
      out.write("            const menu = dropdown.querySelector('.año-dd');\n");
      out.write("            const options = dropdown.querySelectorAll('.año-dd li');\n");
      out.write("            const selected = dropdown.querySelector('.selected-año');\n");
      out.write("\n");
      out.write("            select.addEventListener('click', () => {\n");
      out.write("                select.classList.toggle('select-clicked');\n");
      out.write("                caret.classList.toggle('caret-rotate');\n");
      out.write("                menu.classList.toggle('año-dd-open');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            options.forEach(option => {\n");
      out.write("                option.addEventListener('click', () => {\n");
      out.write("                    selected.innerText = option.innerText;\n");
      out.write("                    select.classList.remove('select-clicked');\n");
      out.write("                    caret.classList.remove('caret-rotate');\n");
      out.write("                    menu.classList.remove('año-dd-open');\n");
      out.write("\n");
      out.write("                    options.forEach(option => {\n");
      out.write("                        option.classList.remove('active');\n");
      out.write("                    });\n");
      out.write("                    option.classList.add('active');\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
